# Generated by Django 5.2.5 on 2025-10-26 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_studentprofile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='Lecturer', max_length=100)),
                ('department', models.CharField(default='CSE', max_length=100)),
                ('seniority_rank', models.PositiveIntegerField(default=1, help_text='1 = Most Senior, higher number = more junior')),
                ('image', models.ImageField(blank=True, null=True, upload_to='faculty_profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_assigned', models.PositiveIntegerField(default=1)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.thesisgroup')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='faculty_feedback/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supervision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='faculty.supervision')),
            ],
        ),
    ]
