# Generated by Django 5.2.5 on 2025-10-26 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='image',
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='seniority_rank',
            field=models.PositiveIntegerField(help_text='1 = most senior, higher number = junior'),
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supervision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='faculty.supervision')),
            ],
        ),
    ]
