# Generated by Django 5.2.7 on 2025-10-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_thesisgroup_thesissubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(default='default_profile.jpg', upload_to='profile_pics/'),
        ),
    ]
