# Generated by Django 5.2.7 on 2025-10-26 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_image'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='accounts.thesissubmission'),
        ),
    ]
